### ISSUE TITLE
Keyboard hides when use $ionicScrollDelegate

### ISSUE THREAD

**Issue by eve-amandine** [driftyco/ionic-plugin-keyboard#101]
Hi,
When the keyboard is showed (in the event native.keyboardshow), I'm running a method of $ionicScrollDelegate, and this line hide the keyboard.
At the beginning I thought it was because I'm running a "scrollBottom" but I've noticed it have the same behavior with "scrollTop", even if I run this event with a "$getByHandle('mainScroll')" (with mainScroll is the ion-content). Why?
Am I missing something or it's an issue?

**Comment by eve-amandine** [comment]
Anybody looks the issues, seriously??

**Comment by tlancina** [comment]
Hey there, this sounds like an Ionic framework issue, not a keyboard plugin issue.  Feel free to post a codepen reproducing the issue, along with what device and OS you're using over there: https://github.com/driftyco/ionic/issues (or here if you think it _is_ a plugin issue and I'll take a look to see if it needs to be re-opened). Thanks!
