### ISSUE TITLE
Hide accessory bar not working on iOS 8.2

### ISSUE THREAD

**Issue by JakeSchieber** [driftyco/ionic-plugin-keyboard#103]
Although it works while running in the iOS simulator
cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
Does not successfully hide the iOS accessory bar on an iPhone 6+ running iOS 8.2.

The application itself was built on the side menu starter app.The app was distributed to the test phone using the ionic view app. I have seen this issue reported on a few other threads by other users as well.

**Comment by JakeSchieber** [comment]
After looking into this further I discovered that the function does successfully hide the accessory bar but
if (window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
}
was never firing as window.cordova was still set to null even after ionic platform had become ready. Do you have any information on why this would be the case? The base app.js seems to be pretty standard across the board.

**Comment by tlancina** [comment]
If you're using View, it's a known issue, you can cheat it with a small workaround: https://github.com/driftyco/ionic-view-issues/issues/52#issuecomment-99250866
