### ISSUE TITLE
Dark iOS keyboard theme

### ISSUE THREAD

**Issue by julesmoretti** [driftyco/ionic-plugin-keyboard#107]
Hello again.

I know that your plugin does not seem to support such feature. But I was wondering if you guys knew how to achieve such result?

Again thank you so much and great work by the way!

**Comment by ericraio** [comment]
The plugin used to have support for a dark theme but they took it out for some reason...it would be awesome if it were re-enabled.

**Comment by markoshust** [comment]
Perhaps this ticket should be reopened? Info given from http://stackoverflow.com/questions/31084058/cordova-ios-dark-keyboard/34569410#34569410
