### ISSUE TITLE
keyboard works after double click

### ISSUE THREAD

**Issue by mubasshir** [driftyco/ionic-plugin-keyboard#109]
I'm having this quite unique problem. I have to 2 fields namely email and password. When I select email, keyboard opens and I can type. Next I click on password, though it has focus but I can't type anything else (Keyboard still opened + when I type on keyboard those character popups appear)

Now either I have to close Keyboard or again touch on email(focus shifts out of password) then touch on password. Now I can type.

Any fix for this?
Can we close/open when focus is shifting to another input/textarea?

**Comment by jorisw** [comment]
I get this too but only when testing remotely with Google Chrome (by using the miniature device in the Chrome inspector to control the phone). On the device, it acts normally.

**Comment by mubasshir** [comment]
nope. It wasn't created new application and problem was same. Finally after so much of debugging, found out full screen was culprit. It was quite strange but removing full screen flag, solved my problem.

**Comment by sanmaozhao** [comment]
I get same issue on iOS. 
@mubasshir , which platform you are encountered this problem, iOS or Android?
And "removing full screen flag" is how to achieve? 

Thank you!
