### ISSUE TITLE
README only states support for iOS...

### ISSUE THREAD

**Issue by xmnboy** [driftyco/ionic-plugin-keyboard#166]
...but plugin.xml file and src directory indicate otherwise. Please update the README.md to properly indicate all supported platforms (along with any specific quirks or features that are unique to those platforms)

**Comment by xmnboy** [comment]
Addendum... it's the initial read that is confusing, where it seems like only iOS is supported. A global "supported platforms" would be useful before going into the various properties and methods. Sorry for the confusion.

**Comment by tlancina** [comment]
Thanks for the issue, I've updated the README to make it clearer when the API reference starts.

**Comment by xmnboy** [comment]
Thanks!
