### ISSUE TITLE
HackishlyHidesInputAccessoryView not found

### ISSUE THREAD

**Issue by floofydoug** [driftyco/ionic-plugin-keyboard#181]
error building projects from latest update: 
`error: property 'hackishlyHidesInputAccessoryView' not found on object of type 'UIWebView *`

```
The following build commands failed:
	CompileC build/Track.build/Debug-iphonesimulator/Track.build/Objects-normal/i386/IonicKeyboard.o Track/Plugins/ionic-plugin-keyboard/IonicKeyboard.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler

```

**Comment by tlancina** [comment]
Could you post the output of `cordova -v` and `cordova plugins ls` please? Thanks!

**Comment by floofydoug** [comment]
cordova running version: 5.4.1
keyboard version: 1.0.8

**Comment by tlancina** [comment]
If you do `cordova plugin rm ionic-plugin-keyboard` and then `cordova plugin add ionic-plugin-keyboard` to update, does it go away?

**Comment by floofydoug** [comment]
@tlancina Yup. sorry about that. realized I was running the wrong version.

**Comment by tlancina** [comment]
No worries, glad it's working! Going to close the issue, but let us know if you're still having problems, thanks!
