### ISSUE TITLE
Provide tag for versions 2.0.0 and 2.0.1

### ISSUE THREAD

**Issue by R1Daneel** [driftyco/ionic-plugin-keyboard#182]
Could you please release new tags for version 2.0.0 and 2.0.1 of the plugin?

**Comment by tlancina** [comment]
Done! This really needs to be automated...

2.0.0 was a bad release, so I didn't do it, but if you need it for some reason let me know, thanks!

**Comment by R1Daneel** [comment]
Thank you so much.
