### ISSUE TITLE
Question: Are pull requests being accepted and would it make sense for me to come up with one?

### ISSUE THREAD

**Issue by leschirmeur** [driftyco/ionic-plugin-keyboard#195]
We have modified the plugin for our app to solve some issues, i.e.
1) Keyboard height not properly calculated on certain Android devices, i.e. Nexus
2) Changing the keyboard on iOS to or from Emoji keyboard with setting "Keyboards/Predictive" set to "off" does result in wrong keyboard height as a keyboard-change event is not being detected by the plugin

Without having it verified, our code modifications probably solve #192, #160 (1) and #193 (2).

Before adding a pull request I'd like to ask if it's worth spending the effort and if such a pull request has chances to be accepted by the team.

**Comment by benmcmaster** [comment]
That would be awesome. I would love to get those fixes...

**Comment by leschirmeur** [comment]
@benmcmaster I'll wait for a reply from @tlancina first before adding a pull request

**Comment by tlancina** [comment]
Yes definitely, would love to have those two fixed. The plugin hasn't been actively maintained lately, so apologies if it ever appeared that we don't accept PRs!

**Comment by leschirmeur** [comment]
@tlancina It didn't appear to me that you don't accept PRs, I just wanted to ask upfront before investing time. Will add a pull request then, thanks for your reply and - the awesome product :-)

**Comment by danielcrk-cn** [comment]
Those two fixes would be awesome!

**Comment by benmcmaster** [comment]
Any status on this? @tlancina @leschirmeur I would love to get this into my next release!

**Comment by leschirmeur** [comment]
@benmcmaster @tlancina Just added in a pull request

**Comment by benmcmaster** [comment]
@leschirmeur Awesome!!! Thank you!

**Comment by okonon** [comment]
@tlancina can you please merge the above PR?
