### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'cordova.plugins.Keyboard.hide')

### ISSUE THREAD

**Issue by TawabG** [driftyco/ionic-plugin-keyboard#201]
I'm working in Intel XDK IDE, and have been for the last couple of weeks.
All the plugins that I'm implementing are working perfectly fine, except for this one
I keep getting this error: `TypeError: undefined is not an object (evaluating 'cordova.plugins.Keyboard.hide')`

-Yes I did link to cordova.js
-Yes the `<clobbers target="cordova.plugins.Keyboard" />` is set correctly
-Yes I work in one .html file (not multiple)
-Yes I've updated to the lastest cordova ionic plugin.(2.2)

Weird thing is, when i'm testing this on an android phone it works.

Any suggestions are welcome!

**Comment by tony--** [comment]
@TawabG - when do you see this error in Intel XDK?  Is it in the emulator or while debugging or some other time?

**Comment by TawabG** [comment]
I used to get this error when debugging in Intel XDK.
However I noticed that when I actually BUILD the app, the plugin works. So apparently intel XDK doesn't support 3rd party plugins when debugging + simulating inside intel XDK. However, debugging with android does work.

**Comment by tony--** [comment]
@TawabG That is all correct.  Glad you got it worked out!
