### ISSUE TITLE
Android issue when going from input to dropdown

### ISSUE THREAD

**Issue by loomtronic** [driftyco/ionic-plugin-keyboard#210]
In Android (might be in iOS, haven't tested) - when I am typing in a text input and then I decide to jump to a dropdown it opens the dropdown, then closes it to close the keyboard and then opens the dropdown again.  When I select the item in the keyboard, nothing is actually selected and I have to open again to select it

**Comment by loomtronic** [comment]
Hmm seems to happen in ionic view but not in the device emulator

**Comment by onelifemedia** [comment]
This is definitely only in Android. I've tested it.

This wasn't an issue a few months ago. I haven't updated my app, and it just showed up one day. Any help would be greatly appreciated.

**Comment by tlancina** [comment]
Does this happen with the keyboard plugin uninstalled or only when the keyboard plugin is installed?

**Comment by loomtronic** [comment]
@tlancina I can verify it happens when the keyboard is installed, I think I tried to uninstall it and I didn't like the user experience

**Comment by luco** [comment]
+1. Only on android.

@tlancina It happens with plugin installed.

**Comment by loomtronic** [comment]
@luco @onelifemedia  do you have this problem in the actual device or just in ionic view?

**Comment by luco** [comment]
@loomtronic Only happens with ionic.

**Comment by luco** [comment]
@tlancina Installed. Didn't test it with uninstalled plugin.

**Comment by luco** [comment]
@tlancina Any on this? It's really annoying.

**Comment by tlancina** [comment]
@luco does it happen when the plugin is uninstalled as well? That's the test for whether it is a plugin issue or not. If it also happens when the plugin is uninstalled then this can be closed, and an issue should be opened at https://github.com/driftyco/ionic/issues.

**Comment by luco** [comment]
@tlancina When I uninstall it, works perfectly. It's plugin-related.

**Comment by tlancina** [comment]
@luco thanks, next step: could you or someone else post some code reproducing the issue?

**Comment by luco** [comment]
@tlancina Any `select` reproduces the issue.

**Comment by luco** [comment]
@tlancina OK, I just figured that happens without plugin. I'm gonna open an issue on Ionic's repo. Thanks for your support.

**Comment by tlancina** [comment]
@luco sounds good! I'm going to close this, but if you don't mind referencing this issue in the new issue or posting the link to the new issue here it might be helpful to someone in the future, thanks!
