### ISSUE TITLE
`keypress` event never triggered

### ISSUE THREAD

**Issue by onelifemedia** [driftyco/ionic-plugin-keyboard#211]
I need to execute a function on `keypress`. It seems to work in iOS. Doesn't seem to work on Android.

**Comment by tlancina** [comment]
Hey this isn't a keyboard plugin issue so I'm going to close it. From googling it quickly it seems Chrome on Android doesn't support `keypress`, just `keyup` and `keydown` - you might want to try those instead. 

If you're using Ionic and still are having issues, I'd suggest asking on the forums: https://forum.ionicframework.com/.

**Comment by gopi2mohan** [comment]
@onelifemedia  Any update on this issue i am also facing this same issue. 

@tlancina  off course if i try using `keyup` and `keydown` the entered key is shown but in my case i need not to show the key what i have pressed i belive `keypress` is the right way to do but it is not working
