### ISSUE TITLE
No release for 2.2.1

### ISSUE THREAD

**Issue by VolleMelk** [driftyco/ionic-plugin-keyboard#224]
I'm seeing 2.2.1 referenced in several online tutorials, and in your code: https://github.com/driftyco/ionic-plugin-keyboard/commit/011283b781a94ba9db9d87fc9531790fcd8aa7e7

But there is no release/tag for 2.2.1. Is this on purpose? I was updating all my plugins, and I was confused to see 2.2.1 referenced in my config.xml, but the latest release is 2.2.0

**Comment by tlancina** [comment]
Hey thanks for the issue, should be fixed now!
