### ISSUE TITLE
cordova.plugins.Keyboard.disableScroll(false) is not working on android device

### ISSUE THREAD

**Issue by ChrisFuck** [driftyco/ionic-plugin-keyboard#252]

**Comment by R1Daneel** [comment]
reading the doc seems that method is supported just for iOS, Windows

**Comment by ChrisFuck** [comment]
@R1Daneel  thanks man

**Comment by ChrisFuck** [comment]
http://ngcordova.com/docs/plugins/keyboard/
reading this doc , and it shows support IOS and android

**Comment by R1Daneel** [comment]
I think that it refers to the plugin itself then every method has support for some specific platform.
