### ISSUE TITLE
Getting error when input search box is going in and out of focus

### ISSUE THREAD

**Issue by markace1246** [driftyco/ionic-plugin-keyboard#36]
I'm receiving an exception on iOS when going in and our of focus on the input search textbox.  [FATAL] [NONE] Uncaught Exception: TypeError: 'undefined' is not an object (evaluating 'cordova.plugins.Keyboard') at (compiled_code):1

However, I'm able to close the keyboard successfully.
//I added the 4 files to project

//config.xml
    <feature name="Keyboard">
    	<param name="ios-package" value="IonicKeyboard" onload="true" />
    </feature>

//In a javascript controller
   closeKeyboard = function() {
	
	try {
		cordova.exec(null, null, "Keyboard", "close", []);
	}
	catch(err) {
                alert("error occurred")
	}	
};

**Comment by ergovia-mobile** [comment]
I've also had this exception. I looked through the plugin configuration and found out, that the clobbers' target (plugin.xml) was set to "window.Keyboard". I changed it to "window.cordova.plugins.Keyboard" and everything works fine.

/com.ionic.keyboard/plugin.xml :
    <js-module src="www/keyboard.js" name="keyboard">
    	<clobbers target="window.cordova.plugins.Keyboard" />
    </js-module>

**Comment by TawabG** [comment]
I'm still getting this error, and chaning the target did not work :(

Any suggestions?
