### ISSUE TITLE
Consider merging with cordova-plugin-keyboard

### ISSUE THREAD

**Issue by mmocny** [driftyco/ionic-plugin-keyboard#6]
Hey guys, looking forward to trying beta4, but am a bit surprised to see a new keyboard plugin.  Have you heard of [`org.apache.cordova.keyboard`](http://plugins.cordova.io/#/package/org.apache.cordova.keyboard) ([github](https://github.com/apache/cordova-plugins/tree/master/keyboard))?

I understand you may want to present a different interface for your users, so I have a potentially suggestion:
* Add `org.apache.cordova.keyboard` as a `<dependency>` for your plugin
* Provide an ionic interface over top of the cordova calls for the subset of features you want to present to your users
* (Please) Contribute back any functionality you think the existing keyboard plugin lacks

Just a suggestion!

**Comment by tlancina** [comment]
Closing this as Cordova decided to have keyboard be a 3rd party plugin and not a part of core.
