### ISSUE TITLE
Is there a way to set a keyboard type to UIKeyboardTypeTwitter

### ISSUE THREAD

**Issue by ericraio** [driftyco/ionic-plugin-keyboard#76]
I'm building an app where I need to have the "hashtag" key accessible directly when the keyboard is open (think twitter or instagram). I know that - in objectiveC - it's something along the line of UIKeyboardTypeTwitter

**Comment by gudmundurh** [comment]
:+1:  – I'd really like to see this supported as well.

**Comment by ptarjan** [comment]
+1

**Comment by jeppester** [comment]
+1
