### ISSUE TITLE
Prevent keyboard from closing/hiding when clicking "Go"  on Android

### ISSUE THREAD

**Issue by arnelceledonio** [driftyco/ionic-plugin-keyboard#84]
i can use window.addEventListener('native.keyboardhide', somefunction()); and use  cordova.plugins.Keyboard.show();
but  user can see the keyboard hide and show effect w/c is very ugly to see.

**Comment by fenton97** [comment]
Try this https://forum.ionicframework.com/t/possible-to-prevent-keyboard-hiding-when-tapping-a-button/55661/5?u=splinter1997
