### ISSUE TITLE
Error when focusing on input text

### ISSUE THREAD

**Issue by buunguyen** [driftyco/ionic-plugin-keyboard#85]
Every time I clicked on an input text in the simulator, I got this error in the console:
```
error    TypeError: undefined is not an object 
(evaluating 'keyboardActiveElement.getBoundingClientRect'),
http://localhost:8100/vendors/ionic/js/ionic.js, Line: 3988
```
Please help fix.

**Comment by notduncansmith** [comment]
Also getting this error (version `1.0.0-rc.4`).

```
undefined is not an object (evaluating 'keyboardActiveElement.getBoundingClientRect'), http://10.0.1.11:8100/lib/ionic/js/ionic.bundle.js, Line: 3995
```

**Comment by roysG** [comment]
same error for me. :(

**Comment by notduncansmith** [comment]
@tlancina any word from the Ionic team on this?

**Comment by tlancina** [comment]
Updating Ionic should make it I away, this was fixed in https://github.com/driftyco/ionic/commit/a86ec11fbd9d810bc272bc2fbeee92fbf07d6dd5.

**Comment by buunguyen** [comment]
@tlancina thanks. Confirm updating to Ionic 1.0 fixes the issue.

**Comment by roysG** [comment]
i updated to ionic 1.0, but it seems for me that the problem was not solving.


Roy-Mac-11:app Admin$ ionic info

Your system information:

Cordova CLI: 5.0.0
Ionic Version: 1.0.0-rc.4
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
ios-deploy version: 1.4.0
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.10.36
Xcode version: Xcode 6.1 Build version 6A1052d

any reason ?

**Comment by azukileo** [comment]
same error for me. 
TypeError: undefined is not an object (evaluating 'keyboardActiveElement.getBoundingClientRect')
keyboardShowionic.bundle.js:3995
（anonymous 関数）ionic.bundle.js:3946

(ionic version 1.6.1).

**Comment by Gunbit** [comment]
same error for me
Your system information:

Cordova CLI: 4.3.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 1.0.1
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0
ios-sim version: 4.1.1
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 6.4 Build version 6E35b
