### ISSUE TITLE
[Feature] iOS UITextInputTraits in UIWebView

### ISSUE THREAD

**Issue by gastonbesada** [driftyco/ionic-plugin-keyboard#9]
Hi @tlancina Could you study the feasibility to include this functionality in the kb plugin?
http://stackoverflow.com/questions/19961103/uikeyboardappearance-in-uiwebview

It will be great to change returnKeyType & keyboardAppearance.
https://developer.apple.com/library/ios/documentation/uikit/reference/UITextInputTraits_Protocol/Reference/UITextInputTraits.html

Thanks and regards

**Comment by tlancina** [comment]
Re-opening this with the coming of ios9 I'll give it another go :)
