### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by adrienkohlbecker** [driftyco/ionic-plugin-keyboard#91]
Hello,

One of my users got a NullPointerException (reported via Rollbar, I don't have more context on what he was doing with the keyboard, sadly). 
He is running a Staraddict 4, a rebranded ZTE Skate, with android 4.4.2
His app is running ionic rc3, and I'm not calling the plugin in my code

```
java.lang.NullPointerException
at com.ionic.keyboard.IonicKeyboard$2.run (IonicKeyboard.java:75)
at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
at java.lang.Thread.run (Thread.java:841)
```

**Comment by tlancina** [comment]
What version of the plugin are you using? I believe this was fixed in https://github.com/driftyco/ionic-plugin-keyboard/commit/bd1adc9b532512e07c4b6fd5d29a73915d50f64c

**Comment by adrienkohlbecker** [comment]
Ah yes, it seems I'm not up to date. Thanks!
Btw, any news on the screen flickering issue on Android? I'm seeing more reports of this bug, has anyone found a workaround?

**Comment by tlancina** [comment]
Yeah the flickering thing is really annoying.  Unfortunately no updates yet, are there any specific versions of Android or devices that you've been seeing it on?

**Comment by adrienkohlbecker** [comment]
Someone mentioned here #70 it appeared with an update from crosswalk 8 to 9, if I remember correctly the bug started appearing around the same time for me, but I'm not 100% positive. 
I'm testing on a Nexus 5 running 5.0.1 and a Galaxy S2 running 4.2, both with crosswalk (I'm at version 12 now), and both have the bug

**Comment by tlancina** [comment]
Ah the Crosswalk bug, that's probably this: https://crosswalk-project.org/jira/browse/XWALK-3547, there are several links to discussions about it in there.

**Comment by adrienkohlbecker** [comment]
This is it, thanks for the link!
