### ISSUE TITLE
$timeout not defined issue when running on Crosswalk

### ISSUE THREAD

**Issue by aitako** [driftyco/ionic-plugin-keyboard#92]
Hi,

I get this: 

I/chromium( 5033): [INFO:CONSOLE(8)] "Uncaught ReferenceError: $timeout is not defined", source: file:///android_asset/www/lib/ngCordova/dist/ng-cordova.min.js (8) on Android when running crosswalk 10. 

My app freezes up and becomes totally unusably slow when I try to input any text. It only happens on Android 4.1.2 and 4.1.1 from what I can see.

The ngCordova library uses the Ionic Keyboard, so I suspect that something is going south deep inside the stack and I can't figure it out.

Any ideas?

Kindly,
Johann

**Comment by zarko-tg** [comment]
Try and update your ngCordova.js (get the latest version which includes an updated Angular keyboard factory code).
