### ISSUE TITLE
Dark Keyboard commented out?

### ISSUE THREAD

**Issue by etiennea** [driftyco/ionic-plugin-keyboard#93]
I tried uncommenting and it crashed. It's a pitty would be nice! 

Any idea on how to get it to work?

**Comment by aemr3** [comment]
I wonder that too...

**Comment by beauby** [comment]
The feature was removed from iOS 7.1 beta 2.

**Comment by etiennea** [comment]
I have seen dark keyboards in apps far beyond iOS 7.1 beta 2. It was just
removed from the settings but apps can still use them. For example in the
app eyeEm.
