### ISSUE TITLE
Resolve java.lang.NullPointerException

### ISSUE THREAD

**Issue by karlkilgi** [driftyco/ionic-plugin-keyboard#95]
My app gets NP sometimes and crashes.

E/AndroidRuntime(22221): java.lang.NullPointerException
E/AndroidRuntime(22221): at com.ionic.keyboard.IonicKeyboard$2.run(IonicKeyboard.java:75)
E/AndroidRuntime(22221): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(22221): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(22221): at java.lang.Thread.run(Thread.java:864)
W/ActivityManager( 753): Force finishing activity

Code from my android app:
```java
public void run() {
                    //http://stackoverflow.com/a/7696791/1091751
                    InputMethodManager inputManager = (InputMethodManager) cordova.getActivity().getSystemService(Context.INPUT_METHOD_SERVICE);
                    View v = cordova.getActivity().getCurrentFocus();

                    if (v == null) {
                        callbackContext.error("No current focus");
                    } else {
                        inputManager.hideSoftInputFromWindow(v.getWindowToken(), InputMethodManager.HIDE_NOT_ALWAYS);
                        callbackContext.success(); // Thread-safe.
                    }
                }
```

Seems like this fix was'nt enough - https://github.com/driftyco/ionic-plugin-keyboard/pull/39

**Comment by karlkilgi** [comment]
@tlancina could you please take a look at it? :)

Is it possible sometimes that the inputManager is null at this point?

**Comment by tlancina** [comment]
What version of Android, and what are the steps to reproduce it?

**Comment by karlkilgi** [comment]
It happened on 4.4, but i cannot provide any steps to reproduce it, because it happens in random moments after calling $location.path. It happens very rarely, but still happens.
