### ISSUE TITLE
Visual glitch / focus issue with keyboard and Crosswalk

### ISSUE THREAD

**Issue by zarko-tg** [driftyco/ionic-plugin-keyboard#96]
Here we go, this issue has been there for a while and I still haven't seen any solution or attention to it.
The problem is that the whole app view seems to jump/jerk a bit when you tap on an input field or unfocus one.

It is only reproducible with Crosswalk and on an Android device.

To see the problem, create a "blank" template project and add Crosswalk, then add the following in the ion-content section:
```
<div class="list">
  <label class="item item-input">
    <input type="text" placeholder="First Name">
  </label>
  <label class="item item-input">
    <input type="text" placeholder="Last Name">
  </label>
  <label class="item item-input">
    <textarea placeholder="Comments"></textarea>
  </label>
</div>
```
Then build / install on an Android device. Try to tap on any input, then out, in, out, you'll notice the issue. Pretty ugly.

I made an APK in case you want to try it directly: http://1drv.ms/1I48X0A

My system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.11
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
ios-deploy version: 1.7.0 
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.4
Xcode version: Xcode 6.3.2 Build version 6D2105 

Installed browsers:

For android - crosswalk 12.41.296.5

**Comment by Honry** [comment]
I am trying to reproduce this issue, but I do not quite understand the phenomenon maybe cause by I couldn't reproduce it. Then I intend to try your apk, but fail to download it since my poor network, could you please share it from another place easier to access?

**Comment by zarko-tg** [comment]
Yes, the file is about 23MB since Crosswalk is bundled in. While there is nothing I can do about its size or your internet connection you may want to try to download the same from an another download location that I just made available to you:
https://www.dropbox.com/s/lbo6j3c6d7vsjji/kb-problem-debug-unaligned.apk?dl=1

Alternatively you can try to recreate and build the app locally on your computer as I explained in the main description of this issue.

**Comment by zarko-tg** [comment]
@mhartington Could you please at least reproduce/confirm the issue?

**Comment by Honry** [comment]
Fortunately, I succeed to download your apk, but cannot find any abnormity when tapping on the input, then out, in, out...
My device is Nexus 5(Android 4.4.2)

**Comment by zarko-tg** [comment]
See video recoding of the issue here: https://youtu.be/XPDd-ZFIE4k

**Comment by mhartington** [comment]
Hmm, alright seeing this as well. I'll let @tlancina take a look at this.

**Comment by Honry** [comment]
I can reproduce it now by rotating the screen, I suppose the fix from Crosswalk Webview plugin: https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/pull/32/ would be helpful since I couldn't reproduce it after applying the patch.
@zarko-tg, could you have a try?

**Comment by markharding** [comment]
@Honry I just applied that fix and it seems to have resolved the issue for me too

**Comment by zarko-tg** [comment]
Yep, it seems to solve the issue.
Looking forward to a conclusion on the pull request by @Nielsb85.

**Comment by trazek** [comment]
I attempted to apply the CrossWalk patch but am still seeing the jump/jerk issue. Can anyone please detail the steps in applying the patch? 

Thank you.

**Comment by mhartington** [comment]
Is this still an issue?

**Comment by zarko-tg** [comment]
A fix was made and taken further within Crosswalk. Thus I'm closing this thread.

**Comment by spirylics** [comment]
@zarko-tg sorry I'm not sure to understand everything with multiple fork, issue, jira but with fresh cordova, crosswalk, ionic I have this glitch yet. And you ?

**Comment by zarko-tg** [comment]
So @spirylics, pesonally I have patched on of the Crosswalk files locally on my developer machine. Their integration and release procedures are an enigma to me, so I have no idea how or when will their fix arrive. Asking within their Jira case might help you if patching is not an option. I just couldn't afford to wait is the problem has been there for months.

**Comment by spirylics** [comment]
Thanks @zarko-tg

**Comment by zarko-tg** [comment]
Update / to @spirylics:
The latest version of cordova-plugin-crosswalk-webview is out now (ver. 1.3.1). Among few small changes it configures the ANIMATABLE_XWALK_VIEW preference to false by default. Which is basically the fix for this GitHub issue.

https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview

**Comment by spirylics** [comment]
Thanks @zarko-tg , I tested and it works fine !
